# MOVIES RECOMMENDATION ON CONTENT BASED 

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import numpy as np

In [51]:
cv=CountVectorizer()

In [17]:
text=['london paris london','paris paris london']
data=cv.fit_transform(text)

In [18]:
#print(data.toarray())

[[2 1]
 [1 2]]


In [21]:
similarity_score=cosine_similarity(data)

In [22]:
similarity_score

array([[1. , 0.8],
       [0.8, 1. ]])

In [ ]:
#1 mean first sentence is same as itself and it is .8 similar to the second sentence and same for second sentence

In [27]:
data=pd.read_csv('movie_dataset.csv')
print(data.shape)
data.head(2)

(4803, 24)


index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   

                                       homepage     id  \
0                   http://www.avatarmovie.com/  19995   
1  http://disney.go.com/disneypictures/pirates/    285   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   

                                                crew        director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...   James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...  Gore Verbinski  

[2 rows x 24 columns]

In [18]:
#main work
#helper function
def get_title_index(index):
    return data[data.index==index]['title'].values[0]

def get_index_title(title):
    return data[data['title']==title]['index'].values[0]

In [19]:
get_title_index(20)#working of helpers function

'The Amazing Spider-Man'

In [20]:
get_index_title('The Amazing Spider-Man')

20

In [26]:
data.columns

Index(['index', 'budget', 'genres', 'homepage', 'id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count', 'cast', 'crew', 'director'],
      dtype='object')

In [47]:
#now we do features selection
features=['genres','cast','director','keywords']
#fillna coloumns
for feature in features:
    data[feature]=data[feature].fillna('')

In [48]:
def combine_feature(row):
    try:
        return row['genres']+' '+row['director']+' '+row['keywords']+' '+row['cast']
    except:
        print('error',row)
        

In [49]:
data['combine_feature']=data.apply(combine_feature,axis=1)

In [50]:
data.head(2)

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   

                                       homepage     id  \
0                   http://www.avatarmovie.com/  19995   
1  http://disney.go.com/disneypictures/pirates/    285   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   

                                            overview  popularity  ...  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   

                                      title  vote_average vote_count  \
0                                    Avatar           7.2      11800   
1  Pirates of the Caribbean: At World's End           6.9       4500   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   

                                                crew        director  \
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...   James Cameron   
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...  Gore Verbinski   

                                     combine_feature  
0  Action Adventure Fantasy Science Fiction James...  
1  Adventure Fantasy Action Gore Verbinski ocean ...  

[2 rows x 25 columns]

In [52]:
count_matrix=cv.fit_transform(data['combine_feature'])

In [54]:
count_matrix.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [55]:
#making cosine similarities
similar_score=cosine_similarity(count_matrix)

In [57]:
similar_score

array([[1.        , 0.10540926, 0.12038585, ..., 0.        , 0.        ,
        0.        ],
       [0.10540926, 1.        , 0.0761387 , ..., 0.03651484, 0.        ,
        0.        ],
       [0.12038585, 0.0761387 , 1.        , ..., 0.        , 0.11145564,
        0.        ],
       ...,
       [0.        , 0.03651484, 0.        , ..., 1.        , 0.        ,
        0.04264014],
       [0.        , 0.        , 0.11145564, ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.04264014, 0.        ,
        1.        ]])

In [60]:
movies_user_like='Avatar'
index=get_index_title(movies_user_like)
index

0

In [62]:
similar_movies=list(enumerate(similar_score[index]))

In [72]:
sorted_similar_movies=sorted(similar_movies,key=lambda x:x[1],reverse=True)

In [76]:
sorted_similar_movies[:10]

[(0, 1.0000000000000004),
 (94, 0.42339019740572564),
 (2403, 0.3774256780481986),
 (3208, 0.3464101615137755),
 (47, 0.34426518632954817),
 (56, 0.33596842045264647),
 (3158, 0.33333333333333337),
 (2198, 0.31426968052735443),
 (2696, 0.30792014356780045),
 (4401, 0.28867513459481287)]

In [80]:
i=0
for movies in sorted_similar_movies:
    print(get_title_index(movies[0]))
    i+=1
    if i > 50:
        break
    

Avatar
Guardians of the Galaxy
Aliens
Star Wars: Clone Wars: Volume 1
Star Trek Into Darkness
Star Trek Beyond
Alien
Lockout
Jason X
The Helix... Loaded
Moonraker
Planet of the Apes
Galaxy Quest
Gravity
Alien³
Jupiter Ascending
The Wolverine
Silent Running
Zathura: A Space Adventure
Trekkies
Cargo
Wing Commander
Star Trek
Lost in Space
Babylon A.D.
The Fifth Element
Oblivion
Titan A.E.
AVP: Alien vs. Predator
The Empire Strikes Back
Dragonball Evolution
Superman Returns
Divergent
John Carter
The Black Hole
The Ice Pirates
Memoirs of an Invisible Man
Starship Troopers
The Astronaut's Wife
Machete Kills
Soldier
The Abyss
Damnation Alley
Men in Black
Space Cowboys
Space Dogs
The Time Machine
Sheena
Captain America: Civil War
Star Trek: Insurrection
Oz: The Great and Powerful
